#+TITLE: st - simple terminal
#+AUTHOR: Ricardo Gomez

* Simple
This is a fork (not really) of st, a simple terminal emulator for X which sucks less.
[[https://st.suckless.org]]

* Obtain
In order to build st you need the Xlib header files.

Additional required packages:
+ libxft-bgra
+ w3m

* Runing
If you did not install st with make clean install, you must compile the st terminfo entry with the following command:

#+begin_src shell
tic -sx st.info
#+end_src

See the man page for additional details.

* Parche
This fork adds some additional features thanks to these 16 patches.

** Alphac
Now you see me, now you still see me.

+ alpha
+ alpha focus highlight

** Colors
Yellow, blue and red, the lice flag.

+ invert

** Keymap
Vi is at my house, and she doesn't want to go.

+ universcroll
+ vim browse

** System
Serious stuff.

+ anysize
+ sync
+ xclearwin
+ xresources

** Visual
Cool right?, Oh! If I only knew something about being cool.

+ blinking cursor
+ boxdraw
+ font2
+ ligatures
+ undercurl
+ visualbell2
+ w3m

* Credit
This fork was brought to you by these people [[file:./CREDITS][CREDITS]].\\
They did the real work, if it was useful give your thanks to them.
